name: Run Selenium Test

on: [push, pull_request]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: php_login_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, mysqli, dom, curl
        coverage: none

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Wait for MySQL
      run: |
        sudo apt-get install -y mysql-client
        until mysql -h127.0.0.1 -uroot -proot -e "SELECT 1"; do
          echo "Waiting for MySQL..."; sleep 2;
        done

    - name: Import DB schema
      run: |
        mysql -h127.0.0.1 -uroot -proot php_login_db < schema.sql

    - name: Start Selenium ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre unzip wget
        wget https://chromedriver.storage.googleapis.com/122.0.6261.111/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        nohup chromedriver --port=9515 > /dev/null 2>&1 &

    - name: Run Selenium test
      env:
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASS: root
        DB_NAME: php_login_db
        ADMIN_USERNAME: admin
        ADMIN_PASSWORD: 123456
        BASE_URL: http://localhost
      run: |
        php -S localhost:80 -t . &
        sleep 3
        vendor/bin/phpunit --testsuite selenium

