name: Run Selenium Test

on: [push, pull_request]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: php_login_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, mysqli, dom, curl
        coverage: none

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y curl unzip jq default-jre mysql-client

    - name: Install Google Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install matching ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        JSON_URL="https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json"
        CHROMEDRIVER_URL=$(curl -s $JSON_URL | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
        echo "Downloading ChromeDriver from $CHROMEDRIVER_URL"
        curl -sS -o chromedriver.zip "$CHROMEDRIVER_URL"
        unzip chromedriver.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Start Selenium Server
      run: |
        curl -sS -o selenium-server.jar https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.21.0/selenium-server-4.21.0.jar
        nohup java -jar selenium-server.jar standalone > selenium.log 2>&1 &

    - name: Wait for MySQL
      run: |
        until mysql -h127.0.0.1 -uroot -proot -e "SELECT 1"; do
          echo "Waiting for MySQL..."; sleep 2;
        done

    - name: Import DB schema
      run: |
        mysql -h127.0.0.1 -uroot -proot php_login_db < schema.sql

    - name: Install PHP dependencies
      run: composer install

    - name: Start local server on port 8080
      run: php -S localhost:8080 -t . &

    - name: Run Selenium test
      env:
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASS: root
        DB_NAME: php_login_db
        ADMIN_USERNAME: admin
        ADMIN_PASSWORD: 123456
        BASE_URL: http://localhost:8080/php-login-system
      run: |
        sleep 3
        vendor/bin/phpunit --testsuite selenium



